//! Tauri build script. The app ACL is explicit: every command below becomes an
//! `allow-<command>` permission, and `capabilities/ui.json` grants them to the
//! UI webview only. Tab webviews get none.

const COMMANDS: &[&str] = &[
    "app_state",
    "app_ready",
    "prompt_respond",
    "shortcut",
    "tabs_create",
    "tabs_close",
    "tabs_activate",
    "tabs_move",
    "tabs_pin",
    "tabs_mute",
    "tabs_duplicate",
    "tabs_reopen_closed",
    "tabs_snapshot",
    "nav_go",
    "nav_url",
    "nav_back",
    "nav_forward",
    "nav_reload",
    "nav_stop",
    "layout_set_insets",
    "overlay_capture",
    "overlay_hide_content",
    "overlay_show_content",
    "suggest_query",
    "suggest_remove",
    "history_search",
    "history_delete",
    "clear_browsing_data",
    "top_sites",
    "favicon_for",
    "bookmarks_tree",
    "bookmarks_add",
    "bookmarks_update",
    "bookmarks_move",
    "bookmarks_remove",
    "bookmarks_restore",
    "bookmarks_for_url",
    "bookmarks_import_html",
    "bookmarks_export_html",
    "passwords_list",
    "passwords_for_tab",
    "passwords_reveal",
    "passwords_delete",
    "passwords_export",
    "passwords_import_csv",
    "autofill_fill",
    "ext_list",
    "ext_prepare_store",
    "ext_prepare_file",
    "ext_confirm",
    "ext_load_unpacked",
    "ext_remove",
    "ext_set_enabled",
    "ext_set_pinned",
    "ext_open_popup",
    "ext_close_popup",
    "ext_open_options",
    "import_detect",
    "import_choose_folder",
    "import_run",
    "downloads_list",
    "downloads_control",
    "downloads_open",
    "downloads_show_in_folder",
    "downloads_remove",
    "downloads_clear",
    "site_permissions",
    "site_permission_revoke",
    "settings_get",
    "settings_set",
    "find_start",
    "find_step",
    "find_stop",
    "zoom_step",
    "window_minimize",
    "window_toggle_maximize",
    "window_close",
    "window_toggle_fullscreen",
    "window_snap_layouts",
    "memory_set_sampling",
    "memory_sleep_tab",
    "memory_unload_tab",
    "memory_sleep_all",
    "memory_set_max_awake",
    "memory_set_preset",
    "print_page",
    "devtools_open",
    "default_browser_open",
    "default_browser_status",
];

fn main() {
    // Every command must be granted in the capability file, or the UI can't call it.
    let capability = std::fs::read_to_string("capabilities/ui.json").expect("capabilities/ui.json");
    for c in COMMANDS {
        let permission = format!("\"allow-{}\"", c.replace('_', "-"));
        assert!(capability.contains(&permission), "capabilities/ui.json is missing {permission}");
    }
    println!("cargo:rerun-if-changed=capabilities/ui.json");
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .expect("tauri build");
}
